timeout: 1800s
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia.gcr.io/$PROJECT_ID/numeric:latest",
        ".",
      ]
    id: "build-spider-test"
tags:
  - "spider-test"
